### ISSUE TITLE
NetCommons3 と AuthShibboleth プラグインを同時に使用すると、内部エラーが発生する

### ISSUE THREAD

**Issue by ghost** [NetCommons3/AuthShibboleth#3]
NetCommons 3.3.3 に AuthShibboleth （2021年6月2日時点） を組み込んで、Shibboleth認証でログインしようとすると、アカウントのマッピング画面の次で「内部エラー」になる。

【やったこと・おこったこと】
1. README.md にあるインストール方法のとおり、Pluginを組み込んだ。
2. Shibboleth の DiscoveryService は使わないので, app/Plugin/AuthShibboleth/View/Elements/login.ctp の一部を書き換えた。

> // [まだ]ログイン設定で切り替え可能にしたいなぁ
> //$url = array('plugin' => 'auth_shibboleth', 'controller' => 'auth_shibboleth', 'action' => 'discovery'); // コメントアウト
> //$url = SiteSettingUtil::read('AuthShibboleth.wayf_return_url');
> $url = array('plugin' => 'auth_shibboleth', 'controller' => 'auth_shibboleth', 'action' => 'secure'); // 追加: DS使わないから

3. アカウントとのマッピングをするところまでは上手くいくが、その次で内部エラーになる。

> Call to a member function getDefaultStartPage() on null
> エラー: 内部エラーが発生しました。
> Stack Trace
>     APP/Plugin/Auth/Controller/AuthExternalController.php line 164 → AuthAppController->_getDefaultStartPage()
>     APP/Plugin/Auth/Controller/AuthExternalController.php line 100 → AuthExternalController->_exLogin()
>     APP/Plugin/Auth/Controller/AuthExternalController.php line 68 → AuthExternalController->_exloginCall()
>     [internal function] → AuthExternalController->exlogin()
>     CORE/Cake/Controller/Controller.php line 499 → ReflectionMethod->invokeArgs()
>     CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction()
>     CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke()
>     APP/webroot/index.php line 131 → Dispatcher->dispatch()

**Comment by Sunday-Programmer** [comment]
AuthShibboleth ではなくて Auth の問題のようなので Close
